/*
 * Nuvio PS5
 * Copyright (C) 2026 Husam Osman
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
#pragma once
/* Files compiled into the app (ui_assets.c, .incbin). Generated by
 * scripts/gen_assets.py - edit that, not this. */
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct ui_asset {
    const uint8_t *data;
    size_t size;          /* data[size] is a 0 byte (SVG text) */
} ui_asset;

ui_asset ui_asset_font_inter_regular(void);
ui_asset ui_asset_font_inter_medium(void);
ui_asset ui_asset_font_inter_semibold(void);
ui_asset ui_asset_font_inter_bold(void);
ui_asset ui_asset_font_roboto_regular(void);
ui_asset ui_asset_font_roboto_bold(void);
ui_asset ui_asset_font_naskh_regular(void);
ui_asset ui_asset_font_naskh_bold(void);
ui_asset ui_asset_font_noto_emoji(void);
ui_asset ui_asset_font_noto_symbols(void);
ui_asset ui_asset_img_wordmark(void);

#ifdef __cplusplus
}
#endif
