/*
 * Nuvio PS5
 * Copyright (C) 2026 Husam Osman
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
/* Fonts from assets/ (paths relative to app/),
 * compiled into the eboot, so nothing depends on the app's file layout.
 * Generated by scripts/gen_assets.py. */
#include "ui_assets.h"

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_font_inter_regular\nnuvio_blob_font_inter_regular:\n.incbin \"assets/fonts/Inter-Regular.ttf\"\n.byte 0\n.global nuvio_blob_font_inter_regular_end\nnuvio_blob_font_inter_regular_end:\n.previous\n");
extern const uint8_t nuvio_blob_font_inter_regular[], nuvio_blob_font_inter_regular_end[];
ui_asset ui_asset_font_inter_regular(void)
{
    ui_asset a = {nuvio_blob_font_inter_regular, (size_t)(nuvio_blob_font_inter_regular_end - nuvio_blob_font_inter_regular) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_font_inter_medium\nnuvio_blob_font_inter_medium:\n.incbin \"assets/fonts/Inter-Medium.ttf\"\n.byte 0\n.global nuvio_blob_font_inter_medium_end\nnuvio_blob_font_inter_medium_end:\n.previous\n");
extern const uint8_t nuvio_blob_font_inter_medium[], nuvio_blob_font_inter_medium_end[];
ui_asset ui_asset_font_inter_medium(void)
{
    ui_asset a = {nuvio_blob_font_inter_medium, (size_t)(nuvio_blob_font_inter_medium_end - nuvio_blob_font_inter_medium) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_font_inter_semibold\nnuvio_blob_font_inter_semibold:\n.incbin \"assets/fonts/Inter-SemiBold.ttf\"\n.byte 0\n.global nuvio_blob_font_inter_semibold_end\nnuvio_blob_font_inter_semibold_end:\n.previous\n");
extern const uint8_t nuvio_blob_font_inter_semibold[], nuvio_blob_font_inter_semibold_end[];
ui_asset ui_asset_font_inter_semibold(void)
{
    ui_asset a = {nuvio_blob_font_inter_semibold, (size_t)(nuvio_blob_font_inter_semibold_end - nuvio_blob_font_inter_semibold) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_font_inter_bold\nnuvio_blob_font_inter_bold:\n.incbin \"assets/fonts/Inter-Bold.ttf\"\n.byte 0\n.global nuvio_blob_font_inter_bold_end\nnuvio_blob_font_inter_bold_end:\n.previous\n");
extern const uint8_t nuvio_blob_font_inter_bold[], nuvio_blob_font_inter_bold_end[];
ui_asset ui_asset_font_inter_bold(void)
{
    ui_asset a = {nuvio_blob_font_inter_bold, (size_t)(nuvio_blob_font_inter_bold_end - nuvio_blob_font_inter_bold) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_font_roboto_regular\nnuvio_blob_font_roboto_regular:\n.incbin \"assets/fonts/Roboto-Regular.ttf\"\n.byte 0\n.global nuvio_blob_font_roboto_regular_end\nnuvio_blob_font_roboto_regular_end:\n.previous\n");
extern const uint8_t nuvio_blob_font_roboto_regular[], nuvio_blob_font_roboto_regular_end[];
ui_asset ui_asset_font_roboto_regular(void)
{
    ui_asset a = {nuvio_blob_font_roboto_regular, (size_t)(nuvio_blob_font_roboto_regular_end - nuvio_blob_font_roboto_regular) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_font_roboto_bold\nnuvio_blob_font_roboto_bold:\n.incbin \"assets/fonts/Roboto-Bold.ttf\"\n.byte 0\n.global nuvio_blob_font_roboto_bold_end\nnuvio_blob_font_roboto_bold_end:\n.previous\n");
extern const uint8_t nuvio_blob_font_roboto_bold[], nuvio_blob_font_roboto_bold_end[];
ui_asset ui_asset_font_roboto_bold(void)
{
    ui_asset a = {nuvio_blob_font_roboto_bold, (size_t)(nuvio_blob_font_roboto_bold_end - nuvio_blob_font_roboto_bold) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_font_naskh_regular\nnuvio_blob_font_naskh_regular:\n.incbin \"assets/fonts/NotoNaskhArabicUI-Regular.ttf\"\n.byte 0\n.global nuvio_blob_font_naskh_regular_end\nnuvio_blob_font_naskh_regular_end:\n.previous\n");
extern const uint8_t nuvio_blob_font_naskh_regular[], nuvio_blob_font_naskh_regular_end[];
ui_asset ui_asset_font_naskh_regular(void)
{
    ui_asset a = {nuvio_blob_font_naskh_regular, (size_t)(nuvio_blob_font_naskh_regular_end - nuvio_blob_font_naskh_regular) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_font_naskh_bold\nnuvio_blob_font_naskh_bold:\n.incbin \"assets/fonts/NotoNaskhArabicUI-Bold.ttf\"\n.byte 0\n.global nuvio_blob_font_naskh_bold_end\nnuvio_blob_font_naskh_bold_end:\n.previous\n");
extern const uint8_t nuvio_blob_font_naskh_bold[], nuvio_blob_font_naskh_bold_end[];
ui_asset ui_asset_font_naskh_bold(void)
{
    ui_asset a = {nuvio_blob_font_naskh_bold, (size_t)(nuvio_blob_font_naskh_bold_end - nuvio_blob_font_naskh_bold) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_font_noto_emoji\nnuvio_blob_font_noto_emoji:\n.incbin \"assets/fonts/NotoEmoji.ttf\"\n.byte 0\n.global nuvio_blob_font_noto_emoji_end\nnuvio_blob_font_noto_emoji_end:\n.previous\n");
extern const uint8_t nuvio_blob_font_noto_emoji[], nuvio_blob_font_noto_emoji_end[];
ui_asset ui_asset_font_noto_emoji(void)
{
    ui_asset a = {nuvio_blob_font_noto_emoji, (size_t)(nuvio_blob_font_noto_emoji_end - nuvio_blob_font_noto_emoji) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_font_noto_symbols\nnuvio_blob_font_noto_symbols:\n.incbin \"assets/fonts/NotoSansSymbols-Subset.ttf\"\n.byte 0\n.global nuvio_blob_font_noto_symbols_end\nnuvio_blob_font_noto_symbols_end:\n.previous\n");
extern const uint8_t nuvio_blob_font_noto_symbols[], nuvio_blob_font_noto_symbols_end[];
ui_asset ui_asset_font_noto_symbols(void)
{
    ui_asset a = {nuvio_blob_font_noto_symbols, (size_t)(nuvio_blob_font_noto_symbols_end - nuvio_blob_font_noto_symbols) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_img_wordmark\nnuvio_blob_img_wordmark:\n.incbin \"assets/brand/wordmark.png\"\n.byte 0\n.global nuvio_blob_img_wordmark_end\nnuvio_blob_img_wordmark_end:\n.previous\n");
extern const uint8_t nuvio_blob_img_wordmark[], nuvio_blob_img_wordmark_end[];
ui_asset ui_asset_img_wordmark(void)
{
    ui_asset a = {nuvio_blob_img_wordmark, (size_t)(nuvio_blob_img_wordmark_end - nuvio_blob_img_wordmark) - 1};
    return a;
}

