#!/usr/bin/env python3
# Nuvio PS5
# Copyright (C) 2026 Husam Osman
# SPDX-License-Identifier: GPL-3.0-or-later
"""Regenerates src/ui_assets.{h,c}: every file listed below, compiled into
the eboot with .incbin (paths relative to app/, where make runs). Run after
adding or renaming an asset. (Emby5: the old player interface's icons and
wordmark went with it; its own interface draws with shapes.)"""
import os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
FIXED = [
    ("font_inter_regular", "assets/fonts/Inter-Regular.ttf"),
    ("font_inter_medium", "assets/fonts/Inter-Medium.ttf"),
    ("font_inter_semibold", "assets/fonts/Inter-SemiBold.ttf"),
    ("font_inter_bold", "assets/fonts/Inter-Bold.ttf"),
    ("font_roboto_regular", "assets/fonts/Roboto-Regular.ttf"),
    ("font_roboto_bold", "assets/fonts/Roboto-Bold.ttf"),
    ("font_naskh_regular", "assets/fonts/NotoNaskhArabicUI-Regular.ttf"),
    ("font_naskh_bold", "assets/fonts/NotoNaskhArabicUI-Bold.ttf"),
    ("font_noto_emoji", "assets/fonts/NotoEmoji.ttf"),
    # Emby5: symbols the other fonts lack (♪ ♫ ...), a subset of Noto Sans Symbols (SIL OFL)
    ("font_noto_symbols", "assets/fonts/NotoSansSymbols-Subset.ttf"),
    # Emby5: the "Emby5" wordmark (assets/brand/wordmark.png, cropped from wordmark-source.png)
    ("img_wordmark", "assets/brand/wordmark.png"),
    # Emby5: the start-up splash's background - the PS5 home screen's launch picture (pic1.dds)
    ("img_splash", "assets/brand/splash.jpg"),
]


def main():
    os.chdir(ROOT)
    assets = list(FIXED)
    h = ["#pragma once",
         "/* Files compiled into the app (ui_assets.c, .incbin). Generated by",
         " * scripts/gen_assets.py - edit that, not this. */",
         "#include <stddef.h>", "#include <stdint.h>", "",
         "#ifdef __cplusplus", 'extern "C" {', "#endif", "",
         "typedef struct ui_asset {", "    const uint8_t *data;",
         "    size_t size;          /* data[size] is a 0 byte (SVG text) */",
         "} ui_asset;", ""]
    c = ["/* Fonts from assets/ (paths relative to app/),",
         " * compiled into the eboot, so nothing depends on the app's file layout.",
         " * Generated by scripts/gen_assets.py. */",
         '#include "ui_assets.h"', ""]
    for name, path in assets:
        h.append("ui_asset ui_asset_%s(void);" % name)
        c.append('__asm__(".section .rodata\\n.balign 16\\n.global nuvio_blob_%s\\n'
                 'nuvio_blob_%s:\\n.incbin \\"%s\\"\\n.byte 0\\n.global nuvio_blob_%s_end\\n'
                 'nuvio_blob_%s_end:\\n.previous\\n");' % (name, name, path, name, name))
        c.append("extern const uint8_t nuvio_blob_%s[], nuvio_blob_%s_end[];" % (name, name))
        c.append("ui_asset ui_asset_%s(void)\n{\n    ui_asset a = {nuvio_blob_%s, "
                 "(size_t)(nuvio_blob_%s_end - nuvio_blob_%s) - 1};\n    return a;\n}\n"
                 % (name, name, name, name))
    h += ["", "#ifdef __cplusplus", "}", "#endif", ""]
    open("src/ui_assets.h", "w").write("/*\n * Nuvio PS5\n * Copyright (C) 2026 Husam Osman\n * SPDX-License-Identifier: GPL-3.0-or-later\n */\n" + "\n".join(h))
    open("src/ui_assets.c", "w").write("/*\n * Nuvio PS5\n * Copyright (C) 2026 Husam Osman\n * SPDX-License-Identifier: GPL-3.0-or-later\n */\n" + "\n".join(c))
    # The Makefile rebuilds ui_assets.o when any of these change.
    open("build-assets.mk", "w").write(
        "ASSET_FILES := " + " ".join(p for _, p in assets) + "\n")
    print("%d assets" % len(assets))


if __name__ == "__main__":
    main()
